on:
  push:
    branches:
      - main
name: Build and Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Use Node.js ${{ matrix.node-version }} and build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: npm install
      - run: npm run build-indexes
      - run: npm test 
      - run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /code-sampler
      - run: npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: /code-sampler
      - run: touch ./out/.nojekyll
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
